workflows:
  ios-flexr:
    name: FLEXR iOS
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: flexr_asc
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: social.flexr.app
      vars:
        XCODE_PROJECT: "ios/FLEXR.xcodeproj"
        XCODE_SCHEME: "FLEXR"
      xcode: latest
    scripts:
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build ipa
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - pachernegg@gmail.com
        notify:
          success: true
          failure: true
