"""add admin tool: admin_users, photo status, user ban, cascade deletes

Revision ID: 1bb027bbc339
Revises: 2e43f3af04b4
Create Date: 2026-07-16 18:10:37.066945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb027bbc339'
down_revision: Union[str, None] = '2e43f3af04b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('pending', 'approved', 'rejected', name='photostatus').create(op.get_bind(), checkfirst=True)
    op.create_table('admin_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.drop_constraint('blocks_blocker_id_fkey', 'blocks', type_='foreignkey')
    op.drop_constraint('blocks_blocked_id_fkey', 'blocks', type_='foreignkey')
    op.create_foreign_key(None, 'blocks', 'users', ['blocked_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'blocks', 'users', ['blocker_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('matches_user_a_id_fkey', 'matches', type_='foreignkey')
    op.drop_constraint('matches_user_b_id_fkey', 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'users', ['user_b_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'matches', 'users', ['user_a_id'], ['id'], ondelete='CASCADE')
    op.add_column('photos', sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='photostatus'), nullable=False, server_default='pending'))
    op.drop_constraint('photos_user_id_fkey', 'photos', type_='foreignkey')
    op.create_foreign_key(None, 'photos', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('reports_reporter_id_fkey', 'reports', type_='foreignkey')
    op.drop_constraint('reports_reported_id_fkey', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['reported_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reports', 'users', ['reporter_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('swipes_to_user_id_fkey', 'swipes', type_='foreignkey')
    op.drop_constraint('swipes_from_user_id_fkey', 'swipes', type_='foreignkey')
    op.create_foreign_key(None, 'swipes', 'users', ['to_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'swipes', 'users', ['from_user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_banned')
    op.drop_constraint(None, 'swipes', type_='foreignkey')
    op.drop_constraint(None, 'swipes', type_='foreignkey')
    op.create_foreign_key('swipes_from_user_id_fkey', 'swipes', 'users', ['from_user_id'], ['id'])
    op.create_foreign_key('swipes_to_user_id_fkey', 'swipes', 'users', ['to_user_id'], ['id'])
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_reported_id_fkey', 'reports', 'users', ['reported_id'], ['id'])
    op.create_foreign_key('reports_reporter_id_fkey', 'reports', 'users', ['reporter_id'], ['id'])
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.create_foreign_key('photos_user_id_fkey', 'photos', 'users', ['user_id'], ['id'])
    op.drop_column('photos', 'status')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key('matches_user_b_id_fkey', 'matches', 'users', ['user_b_id'], ['id'])
    op.create_foreign_key('matches_user_a_id_fkey', 'matches', 'users', ['user_a_id'], ['id'])
    op.drop_constraint(None, 'blocks', type_='foreignkey')
    op.drop_constraint(None, 'blocks', type_='foreignkey')
    op.create_foreign_key('blocks_blocked_id_fkey', 'blocks', 'users', ['blocked_id'], ['id'])
    op.create_foreign_key('blocks_blocker_id_fkey', 'blocks', 'users', ['blocker_id'], ['id'])
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    sa.Enum('pending', 'approved', 'rejected', name='photostatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
