"""add consent timestamps to users

Revision ID: 2e43f3af04b4
Revises: 44a804bba128
Create Date: 2026-07-14 20:30:16.745977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e43f3af04b4'
down_revision: Union[str, None] = '44a804bba128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Nullable anlegen, bestehende Zeilen befuellen, dann erst NOT NULL erzwingen -
    # sonst schlaegt die Migration an jeder Tabelle mit vorhandenen Nutzer:innen fehl.
    # Hinweis: Fuer Alt-Bestandsnutzer:innen (vor Einfuehrung dieser Einwilligungen)
    # ist der Backfill-Zeitstempel KEIN echter Nachweis einer aktiven Einwilligung -
    # das ist ein bekannter Compliance-Punkt, der vor einem Produktivlauf mit
    # Bestandsdaten separat mit einer Anwaltskanzlei zu klaeren ist (z.B. erneute
    # Einwilligung beim naechsten Login einholen).
    op.add_column('users', sa.Column('sensitive_data_consent_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('withdrawal_waiver_consent_at', sa.DateTime(), nullable=True))
    op.execute(
        "UPDATE users SET sensitive_data_consent_at = created_at, "
        "withdrawal_waiver_consent_at = created_at "
        "WHERE sensitive_data_consent_at IS NULL"
    )
    op.alter_column('users', 'sensitive_data_consent_at', nullable=False)
    op.alter_column('users', 'withdrawal_waiver_consent_at', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'withdrawal_waiver_consent_at')
    op.drop_column('users', 'sensitive_data_consent_at')
    # ### end Alembic commands ###
