"""drop street column, address is plz plus city only

Revision ID: 57ea3032c32e
Revises: 954be059ad52
Create Date: 2026-07-16 18:59:57.431544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ea3032c32e'
down_revision: Union[str, None] = '954be059ad52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'street')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
