"""add plz and street address fields, drop city choices restriction

Revision ID: 954be059ad52
Revises: 1bb027bbc339
Create Date: 2026-07-16 18:43:06.214147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954be059ad52'
down_revision: Union[str, None] = '1bb027bbc339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Nullable anlegen, bestehende Zeilen mit Platzhalter befuellen, dann erst
    # NOT NULL erzwingen - sonst schlaegt die Migration an vorhandenen Nutzer:innen
    # fehl. Betroffene Bestandsnutzer:innen muessten ihre echte Adresse im
    # Profil nachtragen.
    op.add_column('users', sa.Column('plz', sa.String(length=4), nullable=True))
    op.add_column('users', sa.Column('street', sa.String(), nullable=True))
    op.execute("UPDATE users SET plz = '0000', street = 'unbekannt' WHERE plz IS NULL")
    op.alter_column('users', 'plz', nullable=False)
    op.alter_column('users', 'street', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'street')
    op.drop_column('users', 'plz')
    # ### end Alembic commands ###
